### ISSUE TITLE
polvo uses toaster config file?

### ISSUE THREAD

**Issue by G3z** [polvo/polvo#2]
the polvo.coffee file is the same as coffee-toaster while in your test you use a far different version.
i think `src/polvo/generators/config.coffee` needs to be updated

**Comment by arboleya** [comment]
Yes, all generators must to be updated since a lot of things has changed.

In one of the last commits I disabled the generators https://github.com/serpentem/polvo/commit/4d452ca87ade48b2741a166e75fce93e786d30ce

There is some things that still needs to be properly design before I implement the generators again.

I'll let you know when the time has come. :)
