### ISSUE TITLE
css not found when using nocache

### ISSUE THREAD

**Issue by davidpaulrosser** [polvo/polvo#26]
We just started a new project using theoricus which seems to be pulling polvo 5.5 but when saving the CSS the browser returns a 404 for the CSS address with no cache.

![screen shot 2013-09-27 at 12 48 53](https://f.cloud.github.com/assets/435118/1225538/f0279fae-276a-11e3-9e47-1267ad89a881.png)

**Comment by arboleya** [comment]
This is very weird, I couldn't reproduce it here.

![css-ok](https://f.cloud.github.com/assets/26660/1226058/05bed360-2779-11e3-9a31-7c5fe3b1f152.png)

Please tell me exactly which version are you using, if you're using it through Theoricus, you may do something like:

`theoricus/node_modules/polvo/bin/polvo -v`

However, if you still get this problem, try removing the whole `theoricus/node_modules` folder and them running `npm install` inside it again, to force the re-download of all dependencies.

If the problem still persists, please try to give some more tip to investigate this.

In the image I pasted above I just installed a fresh Theoricus version which install the latest Polvo under it, and started the app just fine.

**Comment by davidpaulrosser** [comment]
Hi @arboleya,

I'm using Polvo version 0.5.5 inside Theoricus as a vendor of a Theorcius project. I've temporarily fixed it by switching to Polvo version 0.5.4.

**Comment by arboleya** [comment]
The weirdness remains for me, I see non sense on it.

Anyway, it seems that the 404 was raise for you `app.js` which I didn't understand also. Furthermore, I see you're putting the `app.css` inside the `assets` folder. Shouldn't be a problem but try accessing it from the web-root just in case to see if the error remains.

Tks

**Comment by davidpaulrosser** [comment]
Oh I think I see whats happening now. Assets you see in the url above is actually a controller. So it seems that the css is relative to the current controller.

**Comment by arboleya** [comment]
Try including the `css` with absolute url in your html file `/app.css` instead of `app.css`.

**Comment by davidpaulrosser** [comment]
`app.css` is already defined as absolute in index.html. Could there be something in the refresh change that makes app.css relative?

**Comment by hems** [comment]
I can confirm that's is happening if you refresh your stylesheet and you're not on your "/" URL.

For instance, navigation to a subsection and then saving is giving a 404.

Reverting to polvo 0.5.4 does solve the issue ( which i think is a bit strange ).

Will check better soon so hopefully i can patch it.

**Comment by hems** [comment]
So confirming bug.

I just installed a new one:

git clone https://github.com/theoricus/theoricus.git -b dev
cd theoricus
sudo npm install -g 

the -n test
cd test
the -s
.g mvc articles

#Now go to http://localhost:11235/articles/index

#articles/index.jade

.articles
  h1 articles

#articles/index.styl
.articles
  h1
    color: blue

#CMD + S = error loading app.css

The problem is that you don't have the forward slash at the beginning of the path, then the browser will think you're trying to load articles/app.css instead of /app.css.

You can fix that by adding "/" before data.css_output on https://github.com/polvo/polvo/blob/master/src/core/helpers/reloader.js#L30

The problem then will become: if you mount your website in a subpath ( for instance when we need to dev in a folder inside of an apache server ) it will also not find it cause it will always look for app.css on the root folder.

So i guess, the ideal is to find the "link" which includes the file, get the fullpath, strip the random, add new random, attach a new node.
